In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[0.84933793, 0.96158267, 0.82384322, 0.26211021],
       [0.71748453, 0.33890122, 0.29487554, 0.74545451],
       [0.86179131, 0.46061277, 0.83798025, 0.2776578 ],
       [0.71479206, 0.10080216, 0.12873552, 0.8528495 ]])

## 调用mat()函数可以将数组转化为矩阵

In [3]:
randMat = mat(random.rand(4,4))

In [4]:
randMat

matrix([[0.45089849, 0.40771879, 0.6398522 , 0.5530783 ],
        [0.47163791, 0.40949623, 0.32114082, 0.26665495],
        [0.97808532, 0.68198459, 0.53182707, 0.40085597],
        [0.89261703, 0.30526079, 0.05583877, 0.39491997]])

## 对矩阵进行求逆

In [6]:
invRandMat = randMat.I

In [7]:
invRandMat

matrix([[ 0.29279778, -7.23325806,  3.96870974,  0.44556615],
        [-2.73874849, 13.91593081, -5.06384253, -0.42068768],
        [ 2.10058099, -9.80207189,  5.46877737, -1.87432107],
        [ 1.15816471,  6.97831749, -5.82932061,  2.1152622 ]])

In [8]:
randMat * invRandMat ##求矩阵乘以矩阵的逆

matrix([[ 1.00000000e+00, -1.77635684e-15,  8.88178420e-16,
          1.11022302e-16],
        [ 0.00000000e+00,  1.00000000e+00,  4.44089210e-16,
          0.00000000e+00],
        [ 0.00000000e+00,  1.77635684e-15,  1.00000000e+00,
         -1.11022302e-16],
        [ 1.11022302e-16,  0.00000000e+00,  4.44089210e-16,
          1.00000000e+00]])

## 求单位矩阵得到的误差值

In [9]:
myEye = randMat * invRandMat

In [12]:
myEye - eye(4)##eye(4)表示的就是4x4单位矩阵

matrix([[ 0.00000000e+00, -1.77635684e-15,  8.88178420e-16,
          1.11022302e-16],
        [ 0.00000000e+00,  8.88178420e-16,  4.44089210e-16,
          0.00000000e+00],
        [ 0.00000000e+00,  1.77635684e-15,  0.00000000e+00,
         -1.11022302e-16],
        [ 1.11022302e-16,  0.00000000e+00,  4.44089210e-16,
          0.00000000e+00]])